config/routes.rb
Body::Application.routes.draw do
  resources :ysvps

  resources :yogas

  resources :transactions

  resources :tickets

  resources :tiers do
    resources :tickets
  end

  resources :rsvps

  resources :events do
    resources :rsvps
    resources :tiers
    resources :tickets
  end

  devise_for :vibers
  
  resources :vibers
  
  root :to => 'events#index'

end

app/models/tier.rb
class Tier < ActiveRecord::Base
  belongs_to :event
  belongs_to :ticket
  has_one :viber, :through => :ticket
  belongs_to :contact_person, :class_name => 'Viber'
  
  attr_accessible :contact_person_id, :deadline, :event_id, :name, :price, :quantity
  
  before_create :initialize_remaining_quantity
  
  def initialize_remaining_quantity
    self.remaining_quantity = quantity
  end
  
  def priced_name
    "#{name} - #{price} points"
  end
end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
  # GET /tiers
  # GET /tiers.json
  def index
    @tiers = if params[:event_id]
      @event = Event.find params[:event_id]
      @event.tiers
    else
      Tier.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tiers }
    end
  end

  # GET /tiers/1
  # GET /tiers/1.json
  def show
    @tier = Tier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tier }
    end
  end

  # GET /tiers/new
  # GET /tiers/new.json
  def new
    @tier = Tier.new :event_id => params[:event_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tier }
    end
  end

  # GET /tiers/1/edit
  def edit
    @tier = Tier.find(params[:id])
  end

  # POST /tiers
  # POST /tiers.json
  def create
    @tier = Tier.new(params[:tier])

    respond_to do |format|
      if @tier.save
        format.html { redirect_to event_tier_path(@tier.event, @tier), notice: "#{@tier.name} created: #{@tier.remaining_quantity} tickets added for a total of #{@tier.event.available_ticket_count} tickets still available to #{@tier.event.name}" }
        format.json { render json: @tier, status: :created, location: @tier }
      else
        format.html { render action: "new" }
        format.json { render json: @tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tiers/1
  # PUT /tiers/1.json
  def update
    @tier = Tier.find(params[:id])

    respond_to do |format|
      if @tier.update_attributes(params[:tier])
        format.html { redirect_to @tier, notice: 'Tier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiers/1
  # DELETE /tiers/1.json
  def destroy
    @tier = Tier.find(params[:id])
    @tier.destroy

    respond_to do |format|
      format.html { redirect_to tiers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/views/tiers/_form.html.erb
<%= form_for(@tier, params[:event_id].present? ? {:url => event_tiers_path} : {}) do |f| %>
  <% if @tier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tier.errors.count, "error") %> prohibited this tier from being saved:</h2>

      <ul>
      <% @tier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if @tier.event %>
    <%= f.hidden_field :event_id%>
  <% else %>
    <div class="field">
      <%= f.label :event_id %><br />
      <%= f.select :event_id, options_from_collection_for_select(Event.upcoming, :id, :name) %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :contact_person_id %><br />
    <%= f.select :contact_person_id, options_from_collection_for_select(Viber.alpha_email, :id, :email) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tiers/edit.html.erb
<h1>Editing tier</h1>

<%= render 'form' %>

<%= link_to 'Show', @tier %> |
<%= link_to 'Back', tiers_path %>

app/views/tiers/index.html.erb
<h1>Listing tiers</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Remaining quantity</th>
    <th>Deadline</th>
    <th>Contact person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tiers.each do |tier| %>
  <tr>
    <td><%= link_to tier.event.name, tier.event %></td>
    <td><%= link_to tier.name, tier %></td>
    <td><%= tier.price %></td>
    <td><%= tier.quantity %></td>
    <td><%= tier.remaining_quantity %></td>
    <td><%= tier.deadline %></td>
    <td><%= tier.contact_person.email %></td>
  </tr>
<% end %>
</table>

<br />

<% if params[:event_id] %>
  <%= link_to 'New Tier', new_event_tier_path %>
<% else %>
  <%= link_to 'New Tier', new_tier_path %>
<% end %>

app/views/tiers/new.html.erb
<h1>New tier</h1>

<%= render 'form' %>

<%= link_to 'Back', tiers_path %>

app/views/tiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @tier.event.name %>
</p>

<p>
  <b>Name:</b>
  <%= @tier.name %>
</p>

<p>
  <b>Price:</b>
  <%= @tier.price %> points
</p>

<p>
  <b>Quantity:</b>
  <%= @tier.quantity %>
</p>

<p>
  <b>Remaining quantity:</b>
  <%= @tier.remaining_quantity %>
</p>

<p>
  <b>Deadline:</b>
  <%= @tier.deadline %>
</p>

<p>
  <b>Contact person:</b>
  <%= @tier.contact_person_id %>
</p>


<%= link_to 'Edit', edit_tier_path(@tier) %> |
<%= link_to 'Back', tiers_path %>