config/routes.rb
Body::Application.routes.draw do
  resources :ysvps

  resources :yogas

  resources :transactions

  resources :tickets

  resources :tiers do
    resources :tickets
  end

  resources :rsvps

  resources :events do
    resources :rsvps
    resources :tiers
    resources :tickets
  end

  devise_for :vibers
  
  resources :vibers
  
  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :viber
  has_many :rsvps
  has_many :rsvpd_vibers, :through => :rsvps, :source => :viber
  
  has_many :tiers
  has_many :tickets, :through => :tiers
  
  attr_accessible :description, :end_time, :flyer_image, :name, :public, :start_time, :subtitle, :viber_id
  
  mount_uploader :flyer_image, FlyerUploader
  
  scope :upcoming, lambda {{:order => 'start_time asc', :conditions => ["end_time > ?", Time.now]}}
  scope :visible, :conditions => "public > 0"
  
  def available_ticket_count
    tiers.sum :remaining_quantity
  end
  
  def has_tickets_available?
    available_ticket_count > 0
  end
  
  def sold_out?
    tiers.present? && !has_tickets_available?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.visible

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.viber = current_viber

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "#{@event.name} is saved and scheduled." }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => '40x5' %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public %>
  </div>
  <div class="field">
    <%= f.label :flyer_image %><br />
    <%= f.file_field :flyer_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= div_for event do %>
    <div class='flyer'>
      <%= image_tag(event.flyer_image.url, :width => 100) if event.flyer_image.present? %>
    </div>
    <b><%= link_to event.name, event %></b>:
    <%= event.subtitle %>
    <% if someone_is_logged_in %>
      <% if current_viber.rsvp_for_event(event) %>
        <br>Your RSVP: level <%= current_viber.rsvp_for_event(event).sincerity %><br>
      <% else %>
        <br><%= link_to 'RSVP', '#' + dom_id(event, :rsvp), :class => 'fancybox', :id => dom_id(event, :rsvp_to) %>
        <div class='hidden'>
          <%= content_tag :div, :id => dom_id(event, :rsvp) do %>
            <%= form_for event.rsvps.new, :remote => true, :html => {:id => dom_id(event, :rsvp_form_for)} do |f| %>
              <%= f.label :sincerity, 'How excited are you about going?' %>
              <%= f.text_field :sincerity, :size => 4, :placeholder => '1-500' %>
              <%= f.submit :RSVP %>
              <%= f.hidden_field :event_id %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%= event.has_tickets_available? ? link_to('tickets available!', new_event_ticket_path(event)) : (event.sold_out? ? 'sold out!' : 'tickets not yet available.') %>
    <%= "(You have #{current_viber.tickets.for_event(event).count}.)" if current_viber.andand.has_tickets_to_event?(event) %>
    <div class="schedule">
      <%= event.start_time.strftime("%a, *%m/*%d *%I:%M").gsub('*0', '').gsub('*', '') %> - <%= event.end_time.strftime("*%I:%M").gsub('*0', '').gsub('*', '') %>
    </div>
  <% end %>
<% end %>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @event.name %></b>
</p>

<p>
  <%= @event.subtitle %>
</p>

<p>
  <% if @event.has_tickets_available? %>
    <%= link_to 'Get tickets', new_event_ticket_path(@event) %>
  <% end %>
</p>

<i>
  <%= @event.description %>
</i>

<p>
  <%= @event.start_time.strftime("%A, %B *%d from *%I o'clock %p").gsub('*0', '').gsub('*', '') %> until <%= @event.end_time.strftime("*%I o'clock %p on %A, %B *%d").gsub('*0', '').gsub('*', '') %>
</p>

<p>
  <%= image_tag @event.flyer_image.url if @event.flyer_image.present? %>
</p>

<%= link_to 'ticket tiers', event_tiers_path(@event) %>