config/routes.rb
Body::Application.routes.draw do
  resources :ysvps

  resources :yogas

  resources :transactions

  resources :tickets

  resources :tiers do
    resources :tickets
  end

  resources :rsvps

  resources :events do
    resources :rsvps
    resources :tiers
    resources :tickets
  end

  devise_for :vibers
  
  resources :vibers
  
  root :to => 'events#index'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :event
  belongs_to :viber
  
  attr_accessible :event_id, :note, :sincerity, :viber_id
  
  scope :for_event, lambda { |event| event.is_a?(Fixnum) ? {:conditions => {:event_id => event}} : {:conditions => {:event_id => event.id}} }
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = if params[:event_id]
      @event = Event.find params[:event_id]
      @event.rsvps
    else
      Rsvp.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rsvps }
    end
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
    @rsvp = Rsvp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rsvp }
    end
  end

  # GET /rsvps/new
  # GET /rsvps/new.json
  def new
    @rsvp = Rsvp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rsvp }
    end
  end

  # GET /rsvps/1/edit
  def edit
    @rsvp = Rsvp.find(params[:id])
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(params[:rsvp])
    @rsvp.viber = current_viber
    
    respond_to do |format|
      if @rsvp.save
        format.js
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render json: @rsvp, status: :created, location: @rsvp }
      else
        format.html { render action: "new" }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rsvps/1
  # PUT /rsvps/1.json
  def update
    @rsvp = Rsvp.find(params[:id])

    respond_to do |format|
      if @rsvp.update_attributes(params[:rsvp])
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp = Rsvp.find(params[:id])
    @rsvp.destroy

    respond_to do |format|
      format.html { redirect_to rsvps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sincerity %><br />
    <%= f.number_field :sincerity %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note, :size => '40x5' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/create.js.erb
$('#rsvp_to_event_' + <%= @rsvp.event_id %>).replaceWith('<%= @rsvp.sincerity %>');

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<% @rsvps.each do |rsvp| %>
  <%= div_for rsvp do %>
    <%= rsvp.viber.email %>
    <%= link_to rsvp.event.name, event_rsvps_path(rsvp.event) %>
    <%= rsvp.sincerity %>
    <%= rsvp.note %>
    <%= link_to 'Show', rsvp %>
    <%= link_to 'Edit', edit_rsvp_path(rsvp) %>
    <%= link_to 'Destroy', rsvp, confirm: 'Are you sure?', method: :delete %>
  <% end %>
<% end %>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Viber:</b>
  <%= @rsvp.viber_id %>
</p>

<p>
  <b>Event:</b>
  <%= @rsvp.event_id %>
</p>

<p>
  <b>Sincerity:</b>
  <%= @rsvp.sincerity %>
</p>

<p>
  <b>Note:</b>
  <%= @rsvp.note %>
</p>


<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>